---
- hosts: k8s_M
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/pip
  tags: pip


- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    pvName: nfs-pv 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/nfspvc
  tags: nfspvc

- hosts: k8s
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/harbor
  tags: harbor

- hosts: k8s_M[0], localhost
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/helm
  tags: helm

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/istio
  tags: istio

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/dashboard
  tags: dashboard

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
    project_image: harbor.kxfo.com/mall/demo:1.0.0.1
  roles:
    - role: k8s/springboot_demo
  tags: springboot_demo

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/elk
  tags: elk

- hosts: k8s
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    - image_label: app=pay_gateway
    - until_time: 1s
  roles:
    - role: k8s/clean_image
  tags: clean_image

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: k8s/pay/gateway, tags: pay_gateway }
    - { role: k8s/pay/boss, tags: pay_boss }
    - { role: k8s/pay/mch, tags: pay_mch }
    - { role: k8s/pay/sample_shop, tags: pay_sampleShop }
  tags: pay

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/easymock
  tags: easymock
