---
- hosts: k8s_M
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/pip
  tags: pip


- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    pvName: nfs-pv 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/nfspvc
  tags: nfspvc

- hosts: k8s
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/harbor
  tags: harbor

- hosts: k8s_M[0], localhost
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/helm
  tags: helm

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/springboot_demo
  tags: springboot_demo

- hosts: k8s_M[0]
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: k8s/elk
  tags: elk




