---
- hosts: k8s_M
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: k8s/pip
  tags: pip


- hosts: k8s_M[0]
#- hosts: L1
  remote_user: root
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    
  roles:
    - role: k8s/nfspvc
  tags: nfspvc
