---
# 测试

- hosts: all
  remote_user: root
  gather_facts: False
  tasks:
    - name: 测试获取远程机器的ip
      shell: ip addr | egrep ine.*en
      register: ip_out
    - name: 显示返回结果
      debug: var=ip_out.stdout verbosity=0
