- hosts: L
  gather_facts: False
  tasks:
  - name: yum-epel
    yum:
      name: ["epel-release"]
      state: present
  - name: yum-common
    yum:
      name: ["vim", "net-tools", "rsync", "tmux", "mtr", "nmon"]
      state: present
