- name: yum-epel
  yum:
    name: ["epel-release"]
    state: present
- name: yum-common
  yum:
    name: ["vim", "wget", "net-tools", "rsync", "tmux", "mtr", "nmon", "strace", "python3", "python3-pip", "lsof"]
    state: present
