all:
  hosts:
    harbor:
      ansible_host: 10.200.120.236
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
      ansible_python_interpreter: /usr/bin/python2
    nfs:
      ansible_host: 10.200.120.237
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
      ansible_python_interpreter: /usr/bin/python2
    l1:
      ansible_host: 10.200.120.211
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    l2:
      ansible_host: 10.200.120.212
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    l3:
      ansible_host: 10.200.120.213
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    l4:
      ansible_host: 10.200.120.214
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    m1:
      ansible_host: 10.200.120.241
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    m2:
      ansible_host: 10.200.120.242
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n3:
      ansible_host: 10.200.120.243
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n4:
      ansible_host: 10.200.120.244
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n5:
      ansible_host: 10.200.120.245
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n6:
      ansible_host: 10.200.120.246
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n7:
      ansible_host: 10.200.120.247
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    n8:
      ansible_host: 10.200.120.248
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang

  children:
    l:
      hosts:
        l1:
        l2:
        l3:
        l4:
    k8s:
      children:
        k8s_m:
        k8s_n:
    k8s_m:
      hosts:
        m1:
        m2:
    k8s_n:
      hosts:
        n3:
        n4:
        n5:
        n6:
        n7:
        n8:
    nfs_svr:
      hosts:
        nfs:
    nfs_cli:
      children:
        k8s_m:
        k8s_n:
    mysql_m:
      hosts:
        l2:
    mysql_s:
      hosts:
        l3:
      vars:
        master_host_ip: "{{ hostvars['l2']['ansible_default_ipv4']['address'] }}"
        #master_host_ip: "{{ hostvars['L2']['ansible_host'] }}"
    redis_single:
      hosts:
        l1:
          redisPorts: ["6379"]
      vars:
        redisVersion: redis-6.0.6
        redisInstallDir: /home/data
    redis:
      hosts:
        l2:
          redisPorts: ["6379", "6378"]
        l3:
          redisPorts: ["6379", "6378"]
        l4:
          redisPorts: ["6379", "6378"]
      vars:
        redisVersion: redis-6.0.6
        redisInstallDir: /home/data
        redisReplica:
          - {"L3": "6379", "L4": "6378"}
          - {"L4": "6379", "L5": "6378"}
          - {"L5": "6379", "L3": "6378"}
    rabbitmq:
      hosts:
        l1:
    mongodb:
      hosts:
        l2:
    test:
      hosts:
        l2:
