all:
  hosts:
    harbor:
      ansible_host: 10.200.120.236
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    nfs:
      ansible_host: 10.200.120.237
      #ip: 10.200.120.237
      #access_ip: 10.200.120.237
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    L1:
      ansible_host: 10.200.120.211
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
      ansible_python_interpreter: /usr/bin/python2
    L2:
      ansible_host: 10.200.120.212
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    L3:
      ansible_host: 10.200.120.213
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    L4:
      ansible_host: 10.200.120.214
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    L5:
      ansible_host: 10.200.120.215
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    M1:
      ansible_host: 10.200.120.240
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    M2:
      ansible_host: 10.200.120.241
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    N1:
      ansible_host: 10.200.120.245
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    N2:
      ansible_host: 10.200.120.246
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    N3:
      ansible_host: 10.200.120.247
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
    N4:
      ansible_host: 10.200.120.248
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_ssh_pass: chitianxiang
  children:
    L:
      hosts:
        L1:
        L2:
        L3:
        L4:
        L5:
    k8s:
      children:
        k8s_M:
        k8s_N:
    k8s_M:
      hosts:
        M1:
        M2:
    k8s_N:
      hosts:
        N1:
        N2:
        N3:
        N4:
    nfs_svr:
      hosts:
        nfs:
    nfs_cli:
      children:
        k8s_M:
        k8s_N:
    mysql_M:
      hosts:
        L2:
    mysql_S:
      hosts:
        L3:
      vars:
        master_host_ip: "{{ hostvars['L2']['ansible_default_ipv4']['address'] }}"
        #master_host_ip: "{{ hostvars['L2']['ansible_host'] }}"
    redis:
      hosts:
        L3:
          redisPorts: ["6379", "6378"]
        L4:
          redisPorts: ["6379", "6378"]
        L5:
          redisPorts: ["6379", "6378"]
      vars:
        redisVersion: redis-6.0.6
        redisInstallDir: /home/data
        redisReplica:
          - {"L3": "6379", "L4": "6378"}
          - {"L4": "6379", "L5": "6378"}
          - {"L5": "6379", "L3": "6378"}
    rabbitmq:
      hosts:
        L1:
    test:
      hosts:
        L2:
