---
- name: Get Master IP
  set_fact:
    master: "{{ groups.mysql_M[0] }}"

- name: SET 2
  set_fact:
    info_temp: "{{ hostvars[master]['master_status'] }}"
- name: show
  debug: var=info_temp['Position']

- name:  create business user:{{myuser_user}} which only have select priv
  mysql_user:
    #login_host: localhost
    login_password: "{{ root_password }}"
    login_user: root
    name: "{{ myuser_user }}"
    password: "{{ myuser_password }}"
    host: '%'
    login_unix_socket: "{{ mysql_socket }}"
    priv: "*.*:select"
    state: present

- name: Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    master_host: "{{ master_host_ip }}"
    master_user: "{{ rep_user }}"
    master_password: "{{ rep_password }}"
    master_log_file: "{{ info_temp['File'] }}"
    master_log_pos: "{{ info_temp['Position'] }}"

- name: Start slave
  mysql_replication:
    mode: startslave
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
- name: Get Slave
  mysql_replication:
    mode: getslave
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
  register: slave_status

- name: Slave_IO_Running 
  debug: msg="Slave_IO_Running {{ slave_status.Slave_IO_Running }}"

- name: Slave_SQL_Running 
  debug: msg="Slave_SQL_Running {{ slave_status.Slave_SQL_Running }}"

