---
- hosts: L
  remote_user: root
  gather_facts: False
  tasks:
    - name: change tty
      replace:
        path: /etc/sudoers
        regexp: '^#(Defaults\s+requiretty)'
        replace: '\1'
    - name: grep
      shell: grep requiretty /etc/sudoers
      register: show_rlt
    - name: show
      debug: var=show_rlt
  tags: open

- hosts: L
  remote_user: root
  gather_facts: False
  tasks:
    - name: change tty
      replace:
        path: /etc/sudoers
        regexp: '^(Defaults\s+requiretty)'
        replace: '#\1'
    - name: grep
      shell: grep requiretty /etc/sudoers
      register: show_rlt
    - name: show
      debug: var=show_rlt
  tags: close
